//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_Algoritmos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROCESS
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> CPU { get; set; }
        public Nullable<int> TiLLegada { get; set; }
        public Nullable<int> Prioridad { get; set; }
    }

}
